version: '3'
services:
  py:
    build: .
    volumes:
      - /tmp/dataset:/datadir
      - $PWD/step02.py:/main.py:ro
#      - $PWD/step03.py:/main.py:ro
    depends_on:
      - db
  db:
    image: mongo
    command: ["mongod","--noauth"]
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: onlylocalxs
    volumes:
      - /mongodata:/data/db
  webui:
    image: mongo-express
    env_file:
      - .env #ME_CONFIG_BASICAUTH_PASSWORD
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: pwd_in_.env
      ME_CONFIG_MONGODB_SERVER: db
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: onlylocalxs
